baseURL: /
languageCode: it-it
title: ResConDA

params:
    logo: "https://res.cloudinary.com/resconda-it/image/upload/v1646949774/assets/img/logo/favicon.png"
    header_image: "/images/limits.jpg"
    home_title: |
      Azione  
      consapevole
    slogan: |
      Associazione per la  
      **RES**tituzione **CON**sapevole   
      del **D**ebito **A**mbientale
    description: "Acquisire consapevolezza sui numeri in gioco quando si parla di sostenibilità e di risparmio energetico"
    socials:
    - link: "https://facebook.com"
      name: facebook
      icon_tag: "<i class=\"fa-brands fa-facebook fa-2x\"></i>"
    - link: "https://twitter.com"
      name: twitter
      icon_tag: "<i class=\"fa-brands fa-twitter fa-2x\"></i>"
    - link: "https://linkedin.com"
      name: linkedin
      icon_tag: "<i class=\"fa-brands fa-linkedin fa-2x\"></i>"
    - link: "https://instagram.com"
      name: instagram
      icon_tag: "<i class=\"fa-brands fa-instagram fa-2x\"></i>"
    podcast:
      description: |
        L'avventura dell'uomo nella sua lotta per la conquista ed il controllo dell'energia… frecce, fuoco, cibo, petrolio: come l'energia determina le forme della società e dell'economia.
      tagline: Il Podcast di ResConDA
      download_url: https://res.cloudinary.com/resconda-it/video/upload/v1683909094/assets/podcast/
      author: ResConDA
      owner:
        name: Marcello Corongiu
        email: info@resconda.it

menus:
  main:
  # - title: Home
  #   identifier: "home"
  #   url: "/"
  #   weight: 1
  - title: News
    identifier: "articles"
    url: "/articles"
    weight: 20
  - title: Chi siamo
    identifier: "about"
    url: "/about"
    weight: 10
  - title: Le basi
    identifier: "assunti_di_base"
    url: "/assunti-di-base"
    weight: 11
  - title: Contatti
    identifier: "contatti"
    url: "/#contactus"
    weight: 15
  - title: Podcast
    identifier: "podcast"
    url: /episodes
    weight: 30
  
languages:
  it:
    languageName: Italian
    weight: 1
  # en:
  #   languageName: English
  #   weight: 2

taxonomies:
  tag: tags
  class: classes

DefaultContentLanguage: it

outputFormats:
  mp3feed:
    MediaType: "application/rss+xml"
    BaseName: "index"
    path: "/feed/mp3"
    IsHTML: false
    IsPlainText: true
    noUgly: true
    Rel: "alternate"

outputs:
  home:
    - HTML
    - AMP
    - RSS
    - mp3feed