baseURL: /
languageCode: it-it
title: ResConDA

params:
    logo: "https://res.cloudinary.com/resconda-it/image/upload/v1646949774/assets/img/logo/favicon.png"
    header_image: "/images/limits.jpg"
    home_title: |
      Azione  
      consapevole
    slogan: |
      Associazione per la  
      **RES**tituzione **CON**sapevole   
      del **D**ebito **A**mbientale
    socials:
    - link: "https://facebook.com"
      name: facebook
      icon_tag: "<i class=\"fa-brands fa-facebook fa-2x\"></i>"
    - link: "https://twitter.com"
      name: twitter
      icon_tag: "<i class=\"fa-brands fa-twitter fa-2x\"></i>"
    - link: "https://linkedin.com"
      name: linkedin
      icon_tag: "<i class=\"fa-brands fa-linkedin fa-2x\"></i>"
    - link: "https://instagram.com"
      name: instagram
      icon_tag: "<i class=\"fa-brands fa-instagram fa-2x\"></i>"

menus:
  main:
  - title: Home
    identifier: "home"
    url: "/"
    weight: 1
  - title: Blog
    identifier: "articles"
    url: "/articles"
    weight: 20
  - title: Chi siamo
    parent: home
    identifier: "contare"
    url: "/#contare"
    weight: 10
  - title: Numeri
    parent: home
    identifier: "numeri"
    url: "/#shorttermgoal"
    weight: 11
  - title: Contatti
    parent: home
    identifier: "contatti"
    url: "/#contactus"
    weight: 15
  