baseURL: /
languageCode: it-it
title: ResConDA

params:
  logo: "https://res.cloudinary.com/resconda-it/image/upload/v1646949774/assets/img/logo/favicon.png"
  header_image: "/images/limits.jpg"
  home_title: |
    Azione  
    consapevole
  slogan: |
    Associazione per la  
    **RES**tituzione **CON**sapevole   
    del **D**ebito **A**mbientale
  description: "Acquisire consapevolezza sui numeri in gioco quando si parla di sostenibilità e di risparmio energetico"
  socials:
  - link: "https://facebook.com"
    name: facebook
    icon_tag: "<i class=\"fa-brands fa-facebook fa-2x\"></i>"
  - link: "https://twitter.com"
    name: twitter
    icon_tag: "<i class=\"fa-brands fa-twitter fa-2x\"></i>"
  - link: "https://linkedin.com"
    name: linkedin
    icon_tag: "<i class=\"fa-brands fa-linkedin fa-2x\"></i>"
  - link: "https://instagram.com"
    name: instagram
    icon_tag: "<i class=\"fa-brands fa-instagram fa-2x\"></i>"
  search: true
  search_minify: false
  math: true
  ext_links:
    subscription_form_person: https://form.jotform.com/242896877203368
    subscription_form_organization: https://form.jotform.com/243102285113342

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

menus:
  main:
  # - title: Home
  #   identifier: "home"
  #   url: "/"
  #   weight: 1
  - name: News
    identifier: "articles"
    url: "/articles"
    weight: 20
  - name: Chi siamo
    identifier: "about"
    url: "/about"
    weight: 10
  - name: Le basi
    identifier: "assunti_di_base"
    url: "/assunti-di-base"
    weight: 11
  - name: Contatti
    identifier: "contatti"
    url: "/#contactus"
    weight: 15
  - name: Emcoin 
    post: "<i class=\"fa-solid fa-arrow-up-right-from-square fa-xs\"></i>"
    identifier: "emcoin"
    url: "https://emcoin.resconda.it"
    params:
      is_ext: true

outputs:
  home: 
    - HTML
    - JSON
languages:
  it:
    languageName: Italian
    weight: 1
  # en:
  #   languageName: English
  #   weight: 2

taxonomies:
  tag: tags
  class: classes

DefaultContentLanguage: it