omit_categories: true
featured_tags: true
header_image: img/limits.jpg
custom_css: 
    - "css/style.css"
slogan: |
    RESCONDA – Associazione per la 
    REStituzione CONsapevole del 
    Debito Ambientale
home_title: Azione consapevole
menus:
    _merge: none