omit_categories: true
featured_tags: true
slogan: |
    RESCONDA – Associazione per la 
    REStituzione CONsapevole del 
    Debito Ambientale
# addtional_menus:
#     - title: Chi siamo
#       href: "/about"
#     - title: Contatti 
#       href: "/contacts"
menus:
    _merge: none