#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

definitions:
  steps:
    - step: &build
        image: klakegg/hugo:0.105.0-ext
        name: Build Hugo
        script:
          - |
            if [[ "${BITBUCKET_BRANCH}" != "master" ]]; then
              DEBUG="-D"
            fi
            hugo $DEBUG
        artifacts:
          - public/**
    - step: &deploy
        image: instrumentisto/rsync-ssh
        name: Deploy to server
        deployment: staging
        script:
          - |
            if [[ -z "${HETZNER_DEPLOYPATH}" ]] || [[ ! -d "${HETZNER_DEPLOYPATH}" ]]; then
              echo "${HETZNER_DEPLOYPATH} is not a valid folder. Aborting"
              exit 1
            fi
            rsync -e 'ssh -p 44367' -vru --delete public/ ${HETZNER_SSH_USER}@${HETZNER_HOST}:${HETZNER_DEPLOYPATH}/
pipelines:
  branches:
    master:
      - step: *build
      - step:
        <<: *deploy
        deployment: production
  default:
    - step: *build
    - step: *deploy