#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.


pipelines:
  default:
    - step:
        image: trenton/hugo-extended
        name: Build Hugo
        script:
        - ssh -p 44367 ${HETZNER_SSH_USER}@${HETZNER_HOST} date