#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: jguyomard/hugo-builder

pipelines:
  default:
    - step:
        name: Build Hugo
        script:
        - |
          if [[ "${BITBUCKET_BRANCH}" != "master" ]]; then
            DEBUG="-D"
          fi
          hugo $DEBUG
        artifacts:
          - public/**
    - step:
        name: Deploy to server
        script:
        - |
          rsync -vru --delete public/ ${DEPLOY_SSH_USER}@${DEPLOY_HOST}:${DEPLOY_ROOT_FOLDER}/