#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.


pipelines:
  default:
    - step:
        image: trenton/hugo-extended
        name: Build Hugo
        script:
        - |
          if [[ "${BITBUCKET_BRANCH}" != "master" ]]; then
            DEBUG="-D"
          fi
          hugo $DEBUG
        artifacts:
          - public/**
    - step:
        image: instrumentisto/rsync-ssh
        name: Deploy to server
        script:
        - |
          # rsync -vru --delete public/ ${DEPLOY_SSH_USER}@${DEPLOY_HOST}:${DEPLOY_ROOT_FOLDER}/ # old deploy server
          rsync --port=44367 -vru --delete public/ ${HETZNER_SSH_USERPW}@${HETZNER_HOST}:${HETZNER_DEPLOY_ROOT}/