#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

definitions:
  steps:
    - step: &build
        image: klakegg/hugo:0.105.0-ext
        name: Build Hugo
        script:
          - | # build search db
            cd scripts/go/searchdb
            go mod tidy && go build
            cd -
            ./scripts/go/searchdb/searchdb
          - | # build Hugo site
            if [[ "${BITBUCKET_BRANCH}" != "master" ]]; then
              DEBUG="-D"
            fi
            hugo $DEBUG
          - | # place search db into public folder
            mkdir -p public/cgi/res
            cp test.db public/cgi/res/

        artifacts:
          - public/**
    - step: &deploy
        image: instrumentisto/rsync-ssh
        name: Deploy to server
        deployment: staging
        script:
          - |
            if [[ ! "${HETZNER_DEPLOYPATH}" =~ "/home/${HETZNER_SSH_USER}/.*" ]]; then
              echo "${HETZNER_DEPLOYPATH} is not a valid folder. Aborting"
              exit 1
            fi
            rsync -e 'ssh -p 44367' -vru --delete public/ ${HETZNER_SSH_USER}@${HETZNER_HOST}:${HETZNER_DEPLOYPATH}/
pipelines:
  branches:
    master:
      - step: *build
      - step:
          <<: *deploy
          deployment: production
  default:
    - step: *build
    - step: *deploy