#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.15

pipelines:
  default:
    - step:
        name: Build Hugo
        script:
        - |
          hugo -D
    